APP_NAME := subscriber-tests
ARDUINO_LIBS := ../../ AUnit
# EPOXY_CORE_ESP8266 is used because it defines Client when the standard AVR core doesn't ...?
# All we need is that interface and the String implementation, so this "works". Good enough!
EPOXY_CORE := EPOXY_CORE_ESP8266
include ../../deps/EpoxyDuino/EpoxyDuino.mk